const Menu =[{
    id:1,
    image:"waiwai.jpg",
    name:"waiwai",
    category:"Snack",
    price:25,
    description:"Wai Wai is the most popular snacking food available made with flour and spices with best taste and oils.It can be munched in different ways",
},
{
    id:2,
    image:"waiwai.jpg",
    name:"Pizza",
    category:"Lunch",
    price:325,
    description:"Pizza is a dish of Italian origin consisting of a usually round, flat base of leavened wheat-based dough topped with tomatoes, cheese, and often various ...",
},
{
    id:3,
    image:"waiwai.jpg",
    name:"rice",
    category:"Dinner",
    price:225,
    description:"Rice and daal is really a simple and authentic platter to have with of carbs and protein. It consists of a good portion of protein and fibres",
},
{
    id:4,
    image:"waiwai.jpg",
    name:"soup",
    category:"Dinner",
    price:125,
    description:"Soup is the best option for the dinner if one wish to opt or really light and fulfilling food at night. It is really healthy and good for the body",
},
{
    id:5,
    image:"waiwai.jpg",
    name:"momo",
    category:"Lunch",
    price:155,
    description:"One of the  ost popular dish in Nepal and made form flour and filled with veggies and fulfilling achar. It provides an authetic taste to the tastebud ",
},
{
    id:6,
    image:"waiwai.jpg",
    name:"Roti",
    category:"Breakfast",
    price:55,
    description:"A really healthy option for the body is roti made from pure wheat or Bajra. It is highlt filled with fibres and cards needed for the body and provides good metabolism",
},
{
    id:7,
    image:"waiwai.jpg",
    name:"Pakoda",
    category:"Snack",
    price:50,
    description:"Pakoda also known as pakora are a deep fried snack from the Indian Sub-continent. These are made with besan (gram flour), salt, spices ",
},
{
    id:8,
    image:"waiwai.jpg",
    name:"Chowmein",
    category:"Dinner",
    price:150,
    description:"chow mein is one of your favorite Chinese takeout dishes.This one-pan dinner is so satisfying with vegetables, classic chow mein noodles.",
},
{
    id:9,
    image:"waiwai.jpg",
    name:"Burger",
    category:"Dinner",
    price:135,
    description:" hamburger, or simply burger, is a food consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll. ",
},
];

export default Menu;